server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infosystemdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 0103082mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:com/example/demo/mapper/*Mapper.xml


#showSql
#logging:
#  level:
#    com:
#      example:
#        demo:
#          mapper : debug


mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/demo/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity

